################################################################################
# Dummy for Development to include a single file for all compiler projects     #
################################################################################

include CompilerIndependent\Makefile.config
