#######################################################################################################################
# File Name  : Makefile.config                                                                                        #
# Description: This makefile contains the target specific project settings (will be included by Makefile)             #
# Project    : Vector Basic Runtime System                                                                            #
# Module     : BrsHw for platform ARMcommon                                                                           #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# COPYRIGHT                                                                                                           #
#---------------------------------------------------------------------------------------------------------------------#
# Copyright (c) 2020 by Vector Informatik GmbH.                                                  All rights reserved. #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# AUTHOR IDENTITY                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# Name                          Initials      Company                                                                 #
# ----------------------------  ------------  ------------------------------------------------------------------------#
# Jochen Theuer                 visth         Vector Informatik GmbH                                                  #
# Jens Haerer                   visjhr        Vector Informatik GmbH                                                  #
# Benjamin Walter               visbwa        Vector Informatik GmbH                                                  #
#---------------------------------------------------------------------------------------------------------------------#
# REVISION HISTORY                                                                                                    #
#---------------------------------------------------------------------------------------------------------------------#
# Version   Date        Author  Description                                                                           #
# --------  ----------  ------  --------------------------------------------------------------------------------------#
# 1.00.00   2010-08-26  visth   Initial version                                                                       #
# 1.01.00   2010-10-17  visbir  add large                                                                             #
# 2.00.00   2020-07-16  visjhr  Adapted according to Brs_Template 2.02.04                                             #
#           2020-08-07  visbwa  Review; Final adaptions, needed for compile/link test; introduced CPU_CORE            #
#######################################################################################################################

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select Derivative
# possible values are:
#    51      -  Generic 8051 (Core is c51)
#    tc26x   -  TC26x        (Core is c51)
#    tc26xb  -  TC26xB       (Core is c51)
#    tc38x   -  TC38x        (Core is scr2g)
#    tc39x   -  TC39x        (Core is scr2g)
#    tc39xb  -  TC39xB       (Core is scr2g)
#
# This value is directly used as --cpu switch.
#------------------------------------------------------------------------------
DERIVATIVE = tc39x

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Define memory model
# possible values are: SMALL, AUX, LARGE
#------------------------------------------------------------------------------
MEM_MODEL = LARGE
